# Change these first
owner: idrunk65 # Your GitHub organization or username, where this repository lives
repo: games # The name of this repository

sites:
  - name: Panel
    url: https://games.idrunk.fr
  - name: Game 01
    url: http://game01.idrunk.fr
  - name: Game 02
    url: http://game02.idrunk.fr
  - name: Game 03 - Uranium
    url: http://game03.idrunk.fr
  - name: Game 04 - Tsuki
    url: http://game04.idrunk.fr
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: idrunk65.github.io/games
  baseUrl: /games
  logoUrl: https://cdn.discordapp.com/emojis/880113406915538995.webp
  name: iUptime
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /games
    - title: Pannel
      href: https://games.idrunk.fr

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
